language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5
before_script:
  - pear uninstall --nodeps --ignore-errors pear.symfony-project.com/yaml || true
  - pyrus uninstall -f pear.symfony-project.com/yaml || true
script:
  - printf "\n" | pecl install yaml-devel
  - php --ri yaml
