name: Verify Installer

on:
  schedule:
    - cron: "23 15 * * *"
  workflow_dispatch:

jobs:
  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"
          - "8.5"
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libyaml-dev
      - name: Setup PHP
        id: setup-php
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          tools: phpize, php-config
          coverage: none
          extensions: yaml
        env:
          fail-fast: true
          update: true
      - name: Test extension
        run: >-
          curl -o yaml.tgz http://pecl.php.net/get/yaml &&
          tar xzf yaml.tgz &&
          cd yaml-* &&
          phpize &&
          ./configure --with-yaml &&
          make &&
          NO_INTERACTION=1 REPORT_EXIT_STATUS=1 make test
      - name: Extension info
        run: |
          echo PHP ${{ steps.setup-php.outputs.php-version }}
          php --ri yaml
